# .github/workflows/deploy.yml

name: Deploy static HTML to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./  # 정적 HTML 파일이 위치한 폴더 (예: index.html 이 여기에 있어야 함)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
